set(_CATKIN_CURRENT_PACKAGE "gamepack")
set(gamepack_VERSION "0.0.0")
set(gamepack_MAINTAINER "ahmedlasheen <ahmedlasheen@todo.todo>")
set(gamepack_PACKAGE_FORMAT "2")
set(gamepack_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(gamepack_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(gamepack_BUILDTOOL_DEPENDS "catkin")
set(gamepack_BUILDTOOL_EXPORT_DEPENDS )
set(gamepack_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(gamepack_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(gamepack_TEST_DEPENDS )
set(gamepack_DOC_DEPENDS )
set(gamepack_URL_WEBSITE "")
set(gamepack_URL_BUGTRACKER "")
set(gamepack_URL_REPOSITORY "")
set(gamepack_DEPRECATED "")